---
title: "Follow-up from Intro"
author: "John Little"
date: "'r Sys.Date()'"
output: html_notebook
---

## Tidyverse Difference: selective examples

### readr

https://readr.tidyverse.org/

function | package | df v Tibble | string default | parsers | notes 
--- | -------- | --------- | --- | --- | --- 
**read_csv** | [reader](https://readr.tidyverse.org/index.html) (**tidyverse**) | Tibble | character |  dates, times, currencies, percentages, ...  | **faster** 
read.csv | base R | standard df | strings as factors |  | it's fine.

### Tibbles v standard Data Frames

See Grolemund's & Wickham's [_R for Data Science_](http://r4ds.had.co.nz/)

Chapter 11, _Tibbles_  
or
https://tibble.tidyverse.org/

- consistent with tidyverse
- easier viewing (paging)
- simple to convert back and forth:  `as.data.frame()` and `dplyr::as_tibble()`
- Tibbles can be created row-wise:  `dplyr::tribble()`

```{r make-tribble}
my_rowwise_tibble <- dplyr::tribble(
  ~name, ~color, ~amount,
  "circle", "red", 13.6,
  "square", "blue", 7
)

my_rowwise_tibble

```

### Join Types

See _R for Data Science_ chapter 13.4.7
or https://dplyr.tidyverse.org/reference/index.html#section-two-table-verbs 

### Arrange

See _R for Data Science_ chapter 

https://dplyr.tidyverse.org/reference/arrange.html

### Cheat Sheets

RStudio > Help > Cheatsheats > ...

https://www.rstudio.com/resources/cheatsheets/ 

## Other Workshop Topics

### Git / GitHub

- Reproducibility: RStudio and Git (Sep 25, 2018 — 10:00 AM) [registration](https://duke.libcal.com/event/4335577) | [Guide](http://rfun.library.duke.edu/git/) | [Video](https://library.capture.duke.edu/Panopto/Pages/Viewer.aspx?id=36b63692-7297-4f97-b1be-19cd57511d95)
- GitHub and GitLab (Oct 16, 2018 — 10:00 AM) [registration](https://duke.libcal.com/event/4335586) | guide and video (see above)

### Pandas (python)

- Oct. 11, 9-11am.  [Registration](https://duke.libcal.com/event/4350042)

### Shiny

- Nov 7, 2018 — 10:00 AM

    - Shiny App Development with Dr. Mine Çetinkaya-Rundel [registration](https://duke.libcal.com/event/4337320
Wed, 

### Spark

- Spark via R:  [A four park learning series](https://resources.rstudio.com/working-with-spark)

https://spark.rstudio.com/ 


See Also / See Especially the very useful RStudio [Webinar Series](https://resources.rstudio.com/webinars)

## Large Data

