---
title: "ggplot2"
---

```{r setup, include = FALSE, warning = FALSE}
library(htmltools)
tagList(rmarkdown::html_dependency_font_awesome())
```

<p> &nbsp;

## Video

<iframe width="560" height="315" src="https://www.youtube.com/embed/vL3lwGHmiNY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Shareable workshop code

All the shareable code for this ggplot2 workshop can be found in the [workshop_ggplot2 repository on github](https://github.com/libjohn/workshop_ggplot2)

## Slides

From my [workshop on _Visualization with ggplot2_](//slides/index.html)  
Adapated from Garrett Grolemund's _Master the Tidyverse_

## Guide

I worked up a [guide that helps me grok ggplot2 affordances](guide.html)

## ggplot2 documentation

https://ggplot2.tidyverse.org

## Books and resources

- Quick tips on [Visualization principles](https://introds.org/slides/w4_d1-effective-dataviz/w4_d1-effective-dataviz.html#26)
- [ggplot2: Elegant Graphics for Data Analysis.](https://ggplot2-book.org/) Hadley Wickham
- [Data Visualization: A Practical Introduction.](https://socviz.co/lookatdata.html) Kieran Healy
- [Data Visualization with R.](https://rkabacoff.github.io/datavis/) Rob Kabacoff
- [Interactive web-based data visualization with R, plotly, and shiny.](https://plotly-r.com/) Carson Sievert

## Interactive primer & practice exercises

- [RStudio Primers on visualizing data](https://rstudio.cloud/learn/primers/3)
- [Angela Zoss code exercises](https://github.com/amzoss/ggplot2-S20) 
 by [Angela Zoss](https://library.duke.edu/about/directory/staff/angela.zoss)  


