# COMMENT: redirect rules with all the fields expanded
# According to netlify domain management
# https://app.netlify.com/sites/intro2r/settings/domain#domains
# # Redirect default Netlify subdomain to primary domain
# https://intro2r.netlify.com/* https://intro2r.library.duke.edu/:splat 301!
[[redirects]]
  from = "https://intro2r.netlify.com/*"
  to = "https://intro2r.library.duke.edu/:splat"
  status = 301
  force = true
